### ISSUE TITLE
Refactor Goals

### ISSUE THREAD

**Issue by ashmaroli** [ohler55/wabur#12]
This is not a bug report but more of a checklist (~ roadmap) that'll get updated with status of items already present, and with new items as the codebase gets refactored.
It'll additionally serve as a future reference to what's considered optimal for the WABuR library.

- [x] Initialize a Utility Module `WAB::Utils` to handle behavior across `WAB` classes [#10]
- [x] Abstract frequently used methods to the Utility module [#52], [#77]
- [x] Improve readability in `impl/data.rb` by replacing `if..elsif..else` with `case..when` expressions where the check is one variable. [#13]
- [x] Use clause statements to replace conditional branches, where fit [#90]
- [ ] Replace global variables with instance_variables or constants
~~Improve readability by abstracting nested `if..elsif..else` to private methods~~
~~Replace Yoda conditions where conventional conditions would be more optimal~~

Styles
 - [x] Prefer single-quotes consistently unless double-quotes are required for interpolation, special characters [#92]
 - [x] assign to a variable outside the conditional block [#89]

**Comment by ohler55** [comment]
Not much for utils right now but I'm sure that will change as we go along. Good to start it now.

Nothing wrong with nested conditions. I don’t think the fact that conditionals are nested is the right metric for making a separate function. I’d prefer either function gets too large too fit on a page (50-ish lines) or is used in more than one place as the reason for breaking up a function.

I like Yoda style. I see no reason for force a particular order on items being compared. Once you start down that rat hole you get into argument about which side is more constant or which is better. I  don't want to force any order on people and don't want it forced on me either.

I generally prefer single quotes as well when possible. Don't mind that cleanup at all.

**Comment by ashmaroli** [comment]
Re: Yoda style. I don't want to force a particular order but would like to examine the following case and please correct me if I'm wrong:
```ruby
value_class = value.class
if value.nil? ||
  TrueClass == value_class ||
  FalseClass == value_class ||
  Integer == value_class ||
  Float == value_class ||
  String == value_class
x << value
```
Since the RHS is evaluated w.r.t LHS irrespective of the style, wont `value.class` be run for each branch instead reading off the value assigned to variable `value_class` like in the reverse?:
```ruby
  value_class = value.class
  if value.nil? ||
    value_class == TrueClass ||
    value_class == FalseClass ||
    value_class == Integer ||
    value_class == Float ||
    value_class == String
 x << value
```

**Comment by ohler55** [comment]
Like any function, for the evaluation of ```foo == bar``` both arguments need to be evaluated and will. It doesn't matter what order. In the example above ```TrueClass``, as an example is a constant so there is no eval per say other than to use the value. Since value_class is a local variable it is not evaluated either and is most likely in a register on the stack. So maybe a bad example since the only evaluation is the ```==```. 

I thought this is where you were going to use a case statement instead. Yes?

**Comment by ashmaroli** [comment]
> Since value_class is a local variable it is not evaluated either and is most likely in a register on the stack.

I stand corrected regarding this notion. Should've realized myself that local variables are treated the same as constants in an expression *but it would've been evaluated if `value_class` was instead an instance_method*
```ruby
def value_class(value)
  value.class
end
```
Thanks


> I thought this is where you were going to use a case statement instead

Yep, this and similar long ones are being considered for a case expression, too.. but in a separate PR..

**Comment by ohler55** [comment]
Great!

**Comment by ohler55** [comment]
Can this be closed?

**Comment by ashmaroli** [comment]
yeah.. I guess this has outlived its expected time-frame..
Before we close, I found some inconsistency in `Impl::Shell#initialize`
```ruby
def initialize(config)
  @indent       = config['indent'].to_i || 0
  @pre_path     = config[:path_prefix] || '/v1'
  @path_pos     = @pre_path.split('/').length - 1
  base          = config[:base] || '.'
  @model        = Model.new((config['store.dir'] || File.join(base, 'data')).gsub('$BASE', base), indent)
  @type_key     = config[:type_key] || 'kind'
  @logger       = config[:logger]
  @logger.level = config[:verbosity] unless @logger.nil?
  @http_dir     = (config['http.dir'] || File.join(base, 'pages')).gsub('$BASE', base)
  @http_port    = (config['http.port'] || 6363).to_i
  @export_proxy = config['export_proxy']
  @export_proxy = true if @export_proxy.nil? # The default is true if not present.
  [...]
end
```
Some of the keys are accessed as symbols while some are accessed as strings.

**Comment by ohler55** [comment]
I see the `indent` but no others. Either should work but symbols are more direct if the key is not a multi part path.

**Comment by ashmaroli** [comment]
yep.. they do work.. I was shooting for a consistent style..

**Comment by ohler55** [comment]
I'll change in develop for that change.

**Comment by ashmaroli** [comment]
Feel free to do so.. I don't mind at all..

**Comment by ashmaroli** [comment]
> I see the indent but no others.

`config['export_proxy']` also warrants a consideration

**Comment by ohler55** [comment]
got it, thanks
